version: "3.9"  # optional since v1.27.0
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/project
    environment:
      FLASK_APP: api
      FLASK_ENV: development
      PSQL_HOST: database
      PSQL_USER: postgres
      PSQL_PASS: mealplannerpsqlpass
      PSQL_DB:   postgres
    command:
      - pipenv
      - run
      - flask
      - run
      - --host=0.0.0.0
    links:
      - database
  database:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: mealplannerpsqlpass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./dbdata:/var/lib/postgresql/data
