version: "3.9"  # optional since v1.27.0
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/project
    environment:
      FLASK_APP: api
      FLASK_ENV: development
    command:
      - pipenv
      - run
      - flask
      - run
      - --host=0.0.0.0

